### ISSUE TITLE
deactivateShield Fatal Exception: java.lang.NullPointerException: ScreenGuardModule(ScreenGuardModule.java:107)

### ISSUE THREAD

**Issue by levepic** [gbumps/react-native-screenguard#34]
Having some crashes with 0.3.2-stable, a few percent of users, usually at logout, probably when leaving the app and unregister happens:

 100%
Android 11
Device states
100%
background

`
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at com.screenguard.ScreenGuardModule.lambda$deactivateShield$2$com-screenguard-ScreenGuardModule(ScreenGuardModule.java:107)
       at com.screenguard.ScreenGuardModule$$ExternalSyntheticLambda2.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

`
App.js:

function initScreenGuard() {
    try {
        ScreenGuardModule.register(
            //insert any hex color you want here, default black if null or empty
            '#000000',
            () => {
            alert("Screenshots are not allowed!");
        });
    }
    catch (e) {
        console.warn("ScreenGuardModule.register", e);
    }
}

const App = () => {

useEffect(() => {
        initScreenGuard();
        console.log("initScreenGuard()");
        return () => {
            ScreenGuardModule.unregister();
            console.log("ScreenGuardModule.unregister()");
        };        
    }, []);`

**Comment by gbumps** [comment]
please continue and reopen #29.
