### ISSUE TITLE
.registerWithImage crashes the app on Android

### ISSUE THREAD

**Issue by alexuniqkey** [gbumps/react-native-screenguard#52]
Hello! 

First of all, thank you for such a wonderful library, it really has powerful functionality. However, I encountered a problem on the Android platform. When I call the `.registerWithImage` method, my application crashes (I checked on both a device and an emulator). In the `logcat`, I see the following logs at that moment:

``` bash
2024-03-19 10:46:49.727 28231-28231 E/Parcel: Unparcelling of com.screenguard.model.ScreenGuardImageData@52fe663 of type VAL_PARCELABLE consumed 268 bytes, but 272 expected.
android.util.Log$TerribleFailure: Unparcelling of com.screenguard.model.ScreenGuardImageData@52fe663 of type VAL_PARCELABLE consumed 268 bytes, but 272 expected.
at android.util.Log.wtf(Log.java:315)
at android.util.Slog.wtfStack(Slog.java:245)
at android.os.Parcel.readValue(Parcel.java:4350)
at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
at android.os.Parcel$LazyValue.apply(Parcel.java:4445)
at android.os.Parcel$LazyValue.apply(Parcel.java:4404)
at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
at android.os.BaseBundle.getValue(BaseBundle.java:374)
at android.os.BaseBundle.getValue(BaseBundle.java:357)
at android.os.BaseBundle.getValue(BaseBundle.java:350)
at android.os.Bundle.getParcelable(Bundle.java:913)
at android.content.Intent.getParcelableExtra(Intent.java:8941)
at com.screenguard.ScreenGuardColorActivity.onCreate(ScreenGuardColorActivity.java:72)
at android.app.Activity.performCreate(Activity.java:8342)
at android.app.Activity.performCreate(Activity.java:8321)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-03-19 10:46:49.740 28231-28277 W/Parcel: Expecting binder but got null!
2024-03-19 10:46:49.757 28231-28456 D/TrafficStats: tagSocket(73) with statsTag=0xffffffff, statsUid=-1
2024-03-19 10:46:49.761 28231-28277 E/OpenGLRenderer: Unable to match the desired swap behavior.
2024-03-19 10:46:49.935 28231-28458 D/TrafficStats: tagSocket(70) with statsTag=0xffffffff, statsUid=-1
```

The application code is quite simple:

```javascript
const App = () => {
  const dataRequire = {
    height: 122,
    width: 78,
    source: {
      uri: "https://www.icegif.com/wp-content/uploads/2022/09/icegif-386.gif",
    },
    defaultSource: require("shared/assets/svg/logoIcons/signInLogoIcon.svg"),
    backgroundColor: "#FFFFFF",
  };

  return (
    <>
      <Pressable onPress={() => ScreenGuardModule.register("#FFF000")}>
        <Text>.register</Text>
      </Pressable>
      <Pressable onPress={() => ScreenGuardModule.registerWithImage(dataRequire)}>
        <Text>.registerWithImage</Text>
      </Pressable>
    </>
  );
};
```

> Additionally, I noticed that after calling `ScreenGuardModule.register("#FFF000")`, the background color on screen captures and screen recordings always turns black.

My ENV
```
react-native: 0.72.5
react-native-screenguard: 1.0.8-beta 
Google Pixel 4a Android 13
Emulator API 34
```

**Comment by gbumps** [comment]
Hi @alexuniqkey, thanks for reporting

I've received the exact same error above, but app still functioned normally and no corruption on UX side. Anyway, I'll have this fixed soon. Beside, as described in `README.md`, `registerWithImage` is still in experimental on Android, so use it with your own risk.

**Comment by gbumps** [comment]
```
Additionally, I noticed that after calling ScreenGuardModule.register("#FFF000"), the background color on screen captures and screen recordings always turns black.
```

I'm finding another effective way to show this background color without affecting the main application, as the current solution doesn't seems to be working correctly and due to some privacy concern from Google.

**Comment by alexuniqkey** [comment]
> ```
> Additionally, I noticed that after calling ScreenGuardModule.register("#FFF000"), the background color on screen captures and screen recordings always turns black.
> ```
> 
> I'm finding another effective way to show this background color without affecting the main application, as the current solution doesn't seems to be working correctly and due to some privacy concern from Google.

Hello @gbumps, thank you for the response.
Yes, I understand that `.registerWithImage` is still in beta version and stable operation should not be expected. I will eagerly await the new implementation for Android, as well as all the fixes. :)
Thanks!

**Comment by gbumps** [comment]
Hello @alexuniqkey, please install `v1.0.0` and rebuild. 

Thanks!

**Comment by Jianlong-Nie** [comment]
```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/* eslint-disable @typescript-eslint/no-require-imports */
const {
  withAndroidManifest,
  withMainActivity
} = require("@expo/config-plugins")
const fs = require("fs")
const path = require("path")

// https://gbumps.github.io/react-native-screenguard/docs/getting-started/linking/#post-installation-for-android
// A fix for https://github.com/gbumps/react-native-screenguard/issues/70

const addScreenGuardActivity = (config) => {
  return withAndroidManifest(config, async (config) => {
    const { manifest } = config.modResults

    if (!manifest.application || !manifest.application[0]) {
      throw new Error(
        "AndroidManifest does not contain a valid application entry."
      )
    }

    const application = manifest.application[0]

    const screenGuardActivity = {
      $: {
        "android:name": "com.screenguard.ScreenGuardColorActivity",
        "android:theme": "@style/Theme.AppCompat.Translucent",
        "android:configChanges":
          "keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode",
        "android:windowSoftInputMode": "stateAlwaysVisible|adjustResize",
        "android:exported": "false"
      }
    }

    const exists = application.activity?.some(
      (activity) =>
        activity.$["android:name"] ===
        "com.screenguard.ScreenGuardColorActivity"
    )

    if (!exists) {
      application.activity?.push(screenGuardActivity)
    }

    return config
  })
}

const addTranslucentStyle = (config) => {
  return withMainActivity(config, async (config) => {
    const stylesPath = path.join(
      config.modRequest.platformProjectRoot,
      "app/src/main/res/values/styles.xml"
    )

    const translucentStyle = `
      <style name="Theme.AppCompat.Translucent">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:colorBackgroundCacheHint">@null</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowAnimationStyle">@null</item>
        <item name="android:windowSoftInputMode">adjustResize</item>
      </style>
      `

    if (fs.existsSync(stylesPath)) {
      const fileContent = fs.readFileSync(stylesPath, "utf-8")

      if (!fileContent.includes("Theme.AppCompat.Translucent")) {
        const updatedContent = fileContent.replace(
          "</resources>",
          `${translucentStyle}\n</resources>`
        )
        fs.writeFileSync(stylesPath, updatedContent, "utf-8")
      }
    } else {
      const content = `<resources>\n${translucentStyle}\n</resources>`
      fs.writeFileSync(stylesPath, content, "utf-8")
    }

    return config
  })
}

module.exports = function withScreenGuard(config) {
  config = addScreenGuardActivity(config)
  config = addTranslucentStyle(config)
  return config
}

```
works
